name: Update Stock Prices

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 0-23 * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - run: python3 main.py
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_PRICE_DB_ID: ${{ secrets.NOTION_PRICE_DB_ID }}
          NOTION_TRADE_DB_ID: ${{ secrets.NOTION_TRADE_DB_ID }}
          NOTION_ALLOCATION_DB_ID: ${{ secrets.NOTION_ALLOCATION_DB_ID }}
          NOTION_ASSET_DB_ID: ${{ secrets.NOTION_ASSET_DB_ID }}
          NOTION_REBALANCE_DB_ID: ${{ secrets.NOTION_REBALANCE_DB_ID }}
          NOTION_DOMESTIC_STOCK_POSSESSION_DB_ID: ${{ secrets.NOTION_DOMESTIC_STOCK_POSSESSION_DB_ID }}
          NOTION_DIVIDEND_DB_ID: ${{ secrets.NOTION_DIVIDEND_DB_ID }}
          NOTION_REVENUE_DB_ID: ${{ secrets.NOTION_REVENUE_DB_ID }}
          NOTION_KRX_GOLD_INFO_DB_ID: ${{ secrets.NOTION_KRX_GOLD_INFO_DB_ID }}
          NOTION_KRX_GOLD_POSSESSION_DB_ID: ${{ secrets.NOTION_KRX_GOLD_POSSESSION_DB_ID }}
          NOTION_KRX_GOLD_TRADE_DB_ID: ${{ secrets.NOTION_KRX_GOLD_TRADE_DB_ID }}
